updated cicd.yml

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -13,6 +13,20 @@ jobs:
     steps:
     - name: Checkout code
       uses: actions/checkout@v3
+    
+    - name: Install Git LFS and Pull Large Files
+      run: |
+        sudo apt-get update && sudo apt-get install -y git-lfs
+        git lfs install
+        git lfs pull
+    
+    - name: Verify model file
+      run: |
+          if [ ! -f rf_classifier_model.joblib ]; then
+            echo "Model file not found!";
+            exit 1;
+          fi
+          
 
     - name: Set up Python
       uses: actions/setup-python@v4
@@ -35,6 +49,12 @@ jobs:
     - name: Checkout code
       uses: actions/checkout@v3
 
+    - name: Install Git LFS and Pull Large Files
+      run: |
+        sudo apt-get update && sudo apt-get install -y git-lfs
+        git lfs install
+        git lfs pull
+     
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2
 
